spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;Databasename=DaXinJavaBS
    tomcat:
      username: sa
      password: sa123!
  redis:
    host: 192.168.70.32
    port: 6379
    password: 123456
    database: 1

server:
  port: 8081

pojo:
  creator:
    path:
      formPath: C:\Project\Daxin\temp\大信\
      project: C:\Project\Daxin\daxin_bs\domain\src\main\java\com\dxn\model

dxn:
  file:
    upload-path: C:\Project\Upload
    cs-upload-path:
  risk-level:
    file-path: C:\Project\Daxin\RiskLevel.xlsx
  server-name: http://192.168.70.37:8081

workflow:
  path: http://192.168.70.37:8888

cas:
  client-host-url: http://192.168.70.37:8081